excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Vexode.github.io
title: Shock Frame
email: Frank@Vexode.com
author: Vexode
description: My awesome new site
paginate: 3
google_analytics: 